SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS new_vvm_process_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE new_vvm_process_db;

CREATE TABLE institutions (
  institute_id int(11) NOT NULL,
  institute_name varchar(255) NOT NULL,
  institution_code varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO institutions (institute_id, institute_name, institution_code) VALUES
(1, 'SHREE DAMODAR COLLEGE OF COMMERCE & ECONOMICS', 'SDCCE'),
(2, 'GOVIND RAMNATH KARE COLLEGE OF LAW', 'GRKCL'),
(3, 'RAMACRISNA MADEVA SALGAOCAR HIGHER SECONDARY SCHOOL', 'RMS'),
(4, 'VIDYA VIKAS ACADEMY', 'VVA');

CREATE TABLE stg_fees_details (
  stg_id int(11) NOT NULL,
  institution_code varchar(50) NOT NULL,
  uploaded_file_id int(11) NOT NULL,
  institute varchar(255) DEFAULT NULL,
  branch varchar(255) DEFAULT NULL,
  student varchar(255) DEFAULT NULL,
  fees_id varchar(50) DEFAULT NULL,
  fees_scheduled_id varchar(50) DEFAULT NULL,
  e_mail_address varchar(255) DEFAULT NULL,
  mobile_number varchar(20) DEFAULT NULL,
  standard_course varchar(50) DEFAULT NULL,
  division varchar(50) DEFAULT NULL,
  roll_number varchar(50) DEFAULT NULL,
  registration_code varchar(50) DEFAULT NULL,
  fee_head varchar(60) DEFAULT NULL,
  due_date varchar(50) DEFAULT NULL,
  fees_category varchar(50) DEFAULT NULL,
  total_amount decimal(12,2) DEFAULT NULL,
  late_payment_charges decimal(12,2) DEFAULT NULL,
  cgst decimal(12,2) DEFAULT NULL,
  sgst decimal(12,2) DEFAULT NULL,
  igst decimal(12,2) DEFAULT NULL,
  remark text DEFAULT NULL,
  fees_sequence text DEFAULT NULL,
  receipt_number text DEFAULT NULL,
  rrn text DEFAULT NULL,
  student_status varchar(5) DEFAULT NULL,
  payment_status varchar(20) DEFAULT NULL,
  discount_amount decimal(12,2) DEFAULT NULL,
  discount_description text DEFAULT NULL,
  paid_amount decimal(12,2) DEFAULT NULL,
  remaining_amount decimal(12,2) DEFAULT NULL,
  fees_paid_date varchar(20) DEFAULT NULL,
  qfix_reference_number varchar(50) DEFAULT NULL,
  payment_gateway_transaction_id varchar(50) DEFAULT NULL,
  bank_reference_no varchar(50) DEFAULT NULL,
  payment_option varchar(50) DEFAULT NULL,
  payment_mode varchar(50) DEFAULT NULL,
  payment_reference_details varchar(50) DEFAULT NULL,
  payment_details varchar(20) DEFAULT NULL,
  bank_name varchar(255) DEFAULT NULL,
  bank_branch_name varchar(255) DEFAULT NULL,
  ifsc_code varchar(50) DEFAULT NULL,
  cheque_dd_no varchar(50) DEFAULT NULL,
  settlement_date varchar(20) DEFAULT NULL,
  refund_amount decimal(12,2) DEFAULT NULL,
  refund_date varchar(20) DEFAULT NULL,
  refund_status text DEFAULT NULL,
  default_account text DEFAULT NULL,
  vvm_online_offline_live_account decimal(12,2) DEFAULT NULL,
  vva_pre_primary_online_offline_live_account decimal(12,2) DEFAULT NULL,
  rms_secondary_school_76503022 decimal(12,2) DEFAULT NULL,
  sdcce_commerce_economics_76502948 decimal(12,2) DEFAULT NULL,
  sdcce_mcom_76502950 decimal(12,2) DEFAULT NULL,
  sdcce_bba_76502953 decimal(12,2) DEFAULT NULL,
  sdcce_bcom_nsa_76502893 decimal(12,2) DEFAULT NULL,
  sdcce_pgdft_76078365 decimal(12,2) DEFAULT NULL,
  sdcce_b_voc_76502967 decimal(12,2) DEFAULT NULL,
  tuition_fees decimal(12,2) DEFAULT NULL,
  term_fees decimal(12,2) DEFAULT NULL,
  pupils_fund decimal(12,2) DEFAULT NULL,
  activity_fees decimal(12,2) DEFAULT NULL,
  admission_fees decimal(12,2) DEFAULT NULL,
  registration_fees decimal(12,2) DEFAULT NULL,
  development_fund decimal(12,2) DEFAULT NULL,
  refundable_deposit decimal(12,2) DEFAULT NULL,
  general_deposit decimal(12,2) DEFAULT NULL,
  enrolment_fee decimal(12,2) DEFAULT NULL,
  laboratory_deposit decimal(12,2) DEFAULT NULL,
  laboratory_fee decimal(12,2) DEFAULT NULL,
  uni_registration_fees decimal(12,2) DEFAULT NULL,
  library_fees decimal(12,2) DEFAULT NULL,
  gymkhana_fees decimal(12,2) DEFAULT NULL,
  other_fees decimal(12,2) DEFAULT NULL,
  student_aid_fees decimal(12,2) DEFAULT NULL,
  library_deposit decimal(12,2) DEFAULT NULL,
  caution_money_deposit decimal(12,2) DEFAULT NULL,
  lab_fees decimal(12,2) DEFAULT NULL,
  uni_administration_fees decimal(12,2) DEFAULT NULL,
  development_fees decimal(12,2) DEFAULT NULL,
  it_fees decimal(12,2) DEFAULT NULL,
  examination_fees decimal(12,2) DEFAULT NULL,
  pta_fees decimal(12,2) DEFAULT NULL,
  university_registration_fees decimal(12,2) DEFAULT NULL,
  laboratory_fees decimal(12,2) DEFAULT NULL,
  university_administration_fees decimal(12,2) DEFAULT NULL,
  library_id_card_etc decimal(12,2) DEFAULT NULL,
  computer_lab_fees decimal(12,2) DEFAULT NULL,
  information_technology_fees decimal(12,2) DEFAULT NULL,
  iaims_fees_dhe decimal(12,2) DEFAULT NULL,
  iams_fees decimal(12,2) DEFAULT NULL,
  alumni_registration_fees decimal(12,2) DEFAULT NULL,
  academic_restructuring_and_development_fees decimal(12,2) DEFAULT NULL,
  magazine_academic_diary_placement_brochure decimal(12,2) DEFAULT NULL,
  id_card_fees decimal(12,2) DEFAULT NULL,
  iaims_fees decimal(12,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE stg_rms_vva_student_details (
  stg_id int(11) NOT NULL,
  uploaded_file_id int(11) NOT NULL,
  institution_code varchar(50) NOT NULL,
  sl_no int(11) DEFAULT NULL,
  admission_date varchar(15) DEFAULT NULL,
  country varchar(100) DEFAULT NULL,
  date_of_birth varchar(15) DEFAULT NULL,
  nationality varchar(20) DEFAULT NULL,
  student_category varchar(50) DEFAULT NULL,
  batch varchar(20) DEFAULT NULL,
  class varchar(100) DEFAULT NULL,
  course varchar(100) DEFAULT NULL,
  admission_no int(11) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(100) DEFAULT NULL,
  last_name varchar(100) DEFAULT NULL,
  full_name varchar(255) DEFAULT NULL,
  full_name_as_per_leaving_certificate varchar(255) DEFAULT NULL,
  name_as_per_leaving_certificate varchar(255) DEFAULT NULL,
  gender varchar(20) DEFAULT NULL,
  blood_group varchar(10) DEFAULT NULL,
  mother_tongue varchar(50) DEFAULT NULL,
  religion varchar(50) DEFAULT NULL,
  address_line_1 text DEFAULT NULL,
  address_line_2 text DEFAULT NULL,
  city varchar(100) DEFAULT NULL,
  state varchar(100) DEFAULT NULL,
  pin_code int(11) DEFAULT NULL,
  birth_place varchar(100) DEFAULT NULL,
  place_of_birth varchar(255) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  mobile varchar(20) DEFAULT NULL,
  e_mail varchar(255) DEFAULT NULL,
  roll_number int(11) DEFAULT NULL,
  seat_no varchar(100) DEFAULT NULL,
  biometric_id varchar(100) DEFAULT NULL,
  has_attended_school_earlier text DEFAULT NULL,
  sibling_studying_in_vva text DEFAULT NULL,
  marks_obtained_std_x int(11) NOT NULL,
  percentage_obtained_std_x varchar(255) DEFAULT NULL,
  percentage_class_ix varchar(20) DEFAULT NULL,
  percentage_class_x varchar(20) DEFAULT NULL,
  year_passing_ix varchar(255) DEFAULT NULL,
  year_passing_x varchar(255) DEFAULT NULL,
  school_board_name varchar(100) DEFAULT NULL,
  name_of_board varchar(100) DEFAULT NULL,
  name_of_school_attended_earlier varchar(255) DEFAULT NULL,
  name_of_last_school_attended varchar(255) DEFAULT NULL,
  class_xi_xii_subjects text DEFAULT NULL,
  choose_language_ii varchar(100) DEFAULT NULL,
  choose_optional_subject varchar(100) DEFAULT NULL,
  house varchar(100) DEFAULT NULL,
  age_as_on_31_may_2017 varchar(255) DEFAULT NULL,
  aadhar_card_no varchar(20) DEFAULT NULL,
  studentuid varchar(100) DEFAULT NULL,
  bpl varchar(255) DEFAULT NULL,
  extra_curricular_sports text DEFAULT NULL,
  club_the_student_would_like_to_join varchar(100) DEFAULT NULL,
  student_bank_account_no varchar(50) DEFAULT NULL,
  name_of_bank varchar(100) DEFAULT NULL,
  ifsc_code_of_the_bank_branch varchar(20) DEFAULT NULL,
  designation text DEFAULT NULL,
  category varchar(100) DEFAULT NULL,
  gen_reg_no varchar(100) DEFAULT NULL,
  permanent_education_number varchar(100) DEFAULT NULL,
  pen_number varchar(100) DEFAULT NULL,
  prospectus_number varchar(100) DEFAULT NULL,
  height_cm varchar(255) DEFAULT NULL,
  weight_kg varchar(255) DEFAULT NULL,
  father_name varchar(255) DEFAULT NULL,
  mother_name varchar(255) DEFAULT NULL,
  father_first_name varchar(100) DEFAULT NULL,
  father_last_name varchar(100) DEFAULT NULL,
  father_full_name varchar(255) DEFAULT NULL,
  father_username varchar(100) DEFAULT NULL,
  father_dob varchar(255) DEFAULT NULL,
  father_education varchar(100) DEFAULT NULL,
  father_occupation varchar(100) DEFAULT NULL,
  father_income varchar(255) DEFAULT NULL,
  father_email varchar(255) DEFAULT NULL,
  father_office_address_line1 text DEFAULT NULL,
  father_office_address_line2 text DEFAULT NULL,
  father_city varchar(100) DEFAULT NULL,
  father_state varchar(100) DEFAULT NULL,
  father_office_phone1 varchar(20) DEFAULT NULL,
  father_mobile_phone varchar(20) DEFAULT NULL,
  mother_first_name varchar(100) DEFAULT NULL,
  mother_last_name varchar(100) DEFAULT NULL,
  mother_full_name varchar(255) DEFAULT NULL,
  mother_username varchar(100) DEFAULT NULL,
  mother_dob varchar(255) DEFAULT NULL,
  mother_education varchar(100) DEFAULT NULL,
  mother_occupation varchar(100) DEFAULT NULL,
  mother_income varchar(255) DEFAULT NULL,
  mother_email varchar(255) DEFAULT NULL,
  mother_office_address_line1 text DEFAULT NULL,
  mother_office_address_line2 text DEFAULT NULL,
  mother_city varchar(100) DEFAULT NULL,
  mother_state varchar(100) DEFAULT NULL,
  mother_office_phone1 varchar(20) DEFAULT NULL,
  mother_mobile_phone varchar(20) DEFAULT NULL,
  parents_first_name varchar(100) DEFAULT NULL,
  parents_last_name varchar(100) DEFAULT NULL,
  parents_full_name varchar(255) DEFAULT NULL,
  parents_relation varchar(50) DEFAULT NULL,
  parents_username text DEFAULT NULL,
  parents_dob varchar(255) DEFAULT NULL,
  parents_education varchar(100) DEFAULT NULL,
  parents_occupation varchar(100) DEFAULT NULL,
  parents_income varchar(255) DEFAULT NULL,
  parents_email varchar(255) DEFAULT NULL,
  parents_office_address1 text DEFAULT NULL,
  parents_office_address2 text DEFAULT NULL,
  parents_city varchar(100) DEFAULT NULL,
  parents_state varchar(100) DEFAULT NULL,
  parents_office_phone varchar(20) DEFAULT NULL,
  parents_mobile_phone varchar(20) DEFAULT NULL,
  immediate_contact_first_name varchar(100) DEFAULT NULL,
  immediate_contact_last_name varchar(100) DEFAULT NULL,
  immediate_contact_full_name varchar(255) DEFAULT NULL,
  immediate_contact_relation varchar(100) DEFAULT NULL,
  immediate_contact_username varchar(100) DEFAULT NULL,
  immediate_contact_dob varchar(255) DEFAULT NULL,
  immediate_contact_education varchar(100) DEFAULT NULL,
  immediate_contact_occupation varchar(100) DEFAULT NULL,
  immediate_contact_income varchar(255) DEFAULT NULL,
  immediate_contact_email varchar(255) DEFAULT NULL,
  immediate_contact_office_address1 text DEFAULT NULL,
  immediate_contact_office_address2 text DEFAULT NULL,
  immediate_contact_city varchar(100) DEFAULT NULL,
  immediate_contact_state varchar(100) DEFAULT NULL,
  immediate_contact_office_phone varchar(20) DEFAULT NULL,
  immediate_contact_mobile_phone varchar(20) DEFAULT NULL,
  student_previous_data_institution varchar(255) DEFAULT NULL,
  student_previous_data_course varchar(255) DEFAULT NULL,
  student_previous_data_year varchar(255) DEFAULT NULL,
  student_previous_data_total_mark varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE stg_sdcce_grkcl_student_details (
  stg_id int(11) NOT NULL,
  uploaded_file_id int(11) NOT NULL,
  institution_code varchar(50) NOT NULL,
  form_number varchar(50) DEFAULT NULL,
  programme_name varchar(50) DEFAULT NULL,
  ou varchar(50) DEFAULT NULL,
  payment_status varchar(15) DEFAULT NULL,
  admission_scheme varchar(20) DEFAULT NULL,
  enrollment_number int(11) DEFAULT NULL,
  payment_start_date varchar(15) DEFAULT NULL,
  payment_end_date varchar(15) DEFAULT NULL,
  admission_list int(11) DEFAULT NULL,
  admission_status varchar(15) DEFAULT NULL,
  admission_remark varchar(15) DEFAULT NULL,
  admission_category varchar(30) DEFAULT NULL,
  admission_fee_category varchar(10) DEFAULT NULL,
  admission_order_id text DEFAULT NULL,
  admission_transaction_number varchar(20) DEFAULT NULL,
  admission_bank_reference_number text DEFAULT NULL,
  admission_fee_to_be_paid decimal(12,2) DEFAULT NULL,
  admission_fee_paid decimal(12,2) DEFAULT NULL,
  admission_fee_paid_on datetime DEFAULT NULL,
  cancel_request text DEFAULT NULL,
  cancel_requested_on text DEFAULT NULL,
  cancel_requested_reason text DEFAULT NULL,
  do_you_want_to_accept_the_cancellation text DEFAULT NULL,
  cancel_accepted_on text DEFAULT NULL,
  cancel_remarks text DEFAULT NULL,
  withdraw_request text DEFAULT NULL,
  withdraw_requested_on text DEFAULT NULL,
  withdraw_requested_reason text DEFAULT NULL,
  do_you_want_to_accept_the_withrawal text DEFAULT NULL,
  withdraw_accepted_on text DEFAULT NULL,
  withdraw_accepted_remarks text DEFAULT NULL,
  group_applicable varchar(10) DEFAULT NULL,
  faculty_1 text DEFAULT NULL,
  faculty_2 text DEFAULT NULL,
  faculty_3 text DEFAULT NULL,
  subject_1_major text DEFAULT NULL,
  subject_2_major text DEFAULT NULL,
  subject_3_major_elective text DEFAULT NULL,
  subject_4_minor text DEFAULT NULL,
  subject_5_vocational text DEFAULT NULL,
  subject_6_co_curricular text DEFAULT NULL,
  xii_scaled_marks decimal(5,2) DEFAULT NULL,
  merit_points varchar(10) DEFAULT NULL,
  merit_index varchar(10) DEFAULT NULL,
  order_id varchar(20) DEFAULT NULL,
  alias_order_number varchar(20) DEFAULT NULL,
  registration_transaction_id varchar(50) DEFAULT NULL,
  registration_amount_paid decimal(12,2) DEFAULT NULL,
  registration_payment_date varchar(20) DEFAULT NULL,
  submission_status text DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  name_of_the_applicant varchar(255) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  marital_status varchar(15) DEFAULT NULL,
  alternate_mobile varchar(20) DEFAULT NULL,
  dob_day int(11) DEFAULT NULL,
  dob_month int(11) DEFAULT NULL,
  dob_year int(11) DEFAULT NULL,
  age_as_referenced text DEFAULT NULL,
  category varchar(50) DEFAULT NULL,
  sub_category varchar(50) DEFAULT NULL,
  certificate_valid_available text DEFAULT NULL,
  certificate_number text DEFAULT NULL,
  certificate_issuing_date text DEFAULT NULL,
  family_income_ews text DEFAULT NULL,
  blood_group varchar(5) DEFAULT NULL,
  religion varchar(25) DEFAULT NULL,
  are_you_citizen_of_india varchar(5) DEFAULT NULL,
  other_nationality text DEFAULT NULL,
  domicile_of_state text DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  mobile varchar(20) DEFAULT NULL,
  id_proof text DEFAULT NULL,
  id_proof_number text DEFAULT NULL,
  existing_university_student varchar(5) DEFAULT NULL,
  existing_registration_no text DEFAULT NULL,
  existing_college_department_name text DEFAULT NULL,
  existing_university_student_school text DEFAULT NULL,
  existing_uni_student_programme text DEFAULT NULL,
  existing_university_student_year_of_registration text DEFAULT NULL,
  name_of_father varchar(255) DEFAULT NULL,
  father_qualification text DEFAULT NULL,
  father_occupation text DEFAULT NULL,
  father_mobile varchar(20) DEFAULT NULL,
  father_office_address text DEFAULT NULL,
  name_of_mother varchar(255) DEFAULT NULL,
  mother_qualification text DEFAULT NULL,
  mother_occupation text DEFAULT NULL,
  mother_mobile varchar(20) DEFAULT NULL,
  mother_office_address text DEFAULT NULL,
  combined_family_income text DEFAULT NULL,
  pwd_category text DEFAULT NULL,
  pwd_category_other text DEFAULT NULL,
  pwd_percentage_of_disability text DEFAULT NULL,
  kashmiri_migrant text DEFAULT NULL,
  pm_scholarship text DEFAULT NULL,
  ex_service_man text DEFAULT NULL,
  sgc_quota text DEFAULT NULL,
  defence_personal_quota text DEFAULT NULL,
  dependent_of_freedom_fighter text DEFAULT NULL,
  add_line_1 text DEFAULT NULL,
  add_line_2 text DEFAULT NULL,
  city varchar(100) DEFAULT NULL,
  other_city varchar(100) DEFAULT NULL,
  other_state varchar(100) DEFAULT NULL,
  country varchar(100) DEFAULT NULL,
  other_country varchar(100) DEFAULT NULL,
  pincode int(11) DEFAULT NULL,
  permanent_address_line_1 text DEFAULT NULL,
  permanent_address_line_2 text DEFAULT NULL,
  permanent_city text DEFAULT NULL,
  other_permanent_city text DEFAULT NULL,
  permanent_state text DEFAULT NULL,
  other_permanent_state text DEFAULT NULL,
  permanent_country text DEFAULT NULL,
  other_permanent_country text DEFAULT NULL,
  permanent_pincode int(11) DEFAULT NULL,
  x_result_status text DEFAULT NULL,
  x_passing_year text DEFAULT NULL,
  x_percentage text DEFAULT NULL,
  x_name_of_the_institution text DEFAULT NULL,
  x_board text DEFAULT NULL,
  x_subject_combination text DEFAULT NULL,
  x_division text DEFAULT NULL,
  xii_result_status varchar(10) DEFAULT NULL,
  xii_passing_year int(11) DEFAULT NULL,
  xii_stream varchar(50) DEFAULT NULL,
  xii_maximum_marks int(11) DEFAULT NULL,
  xii_marks_obtained int(11) DEFAULT NULL,
  xii_percentage decimal(5,2) DEFAULT NULL,
  xii_name_of_the_institution text DEFAULT NULL,
  xii_board text DEFAULT NULL,
  xii_board_roll_number text DEFAULT NULL,
  xii_subject_combination text DEFAULT NULL,
  xii_division varchar(20) DEFAULT NULL,
  ug_subject_combination text DEFAULT NULL,
  is_ug_done_with_honors text DEFAULT NULL,
  ug_honors_subject_name text DEFAULT NULL,
  ug_univerisity_name text DEFAULT NULL,
  ug_university_name_other text DEFAULT NULL,
  ug_institute_college text DEFAULT NULL,
  ug_reg_number_if_from_this_uni text DEFAULT NULL,
  ug_course_name text DEFAULT NULL,
  ug_division text DEFAULT NULL,
  ug_upload text DEFAULT NULL,
  ug_result_type text DEFAULT NULL,
  any_illness text DEFAULT NULL,
  nature_of_illness text DEFAULT NULL,
  is_ward_of_uni_college_employee text DEFAULT NULL,
  noc_from_employer text DEFAULT NULL,
  urban_rural_semi_urban_metro_area text DEFAULT NULL,
  ward_of_transferred_uni_college_emp text DEFAULT NULL,
  cert_of_transferred_employee text DEFAULT NULL,
  son_daughter_husband_wife_relative_of_paramilitary text DEFAULT NULL,
  paramilitary_relative_certificate text DEFAULT NULL,
  sport_international_level text DEFAULT NULL,
  sport_international_level_cert text DEFAULT NULL,
  medals_inter_uni_state_national_level text DEFAULT NULL,
  medals_inter_uni_state_national_level_cert text DEFAULT NULL,
  participation_national_level_govt_fed text DEFAULT NULL,
  participation_national_level_govt_fed_cert text DEFAULT NULL,
  participation_state_inter_uni_level text DEFAULT NULL,
  participation_state_inter_uni_level_cert text DEFAULT NULL,
  participation_inter_uni_level text DEFAULT NULL,
  participation_inter_uni_level_cert text DEFAULT NULL,
  winner_runner_up_inter_college_level text DEFAULT NULL,
  winner_runner_up_inter_college_level_cert text DEFAULT NULL,
  competition_cert_district_division_level text DEFAULT NULL,
  competition_cert_district_division_level_cert text DEFAULT NULL,
  member_of_sports_team_inter_college_comp text DEFAULT NULL,
  member_of_sports_team_inter_college_comp_cert text DEFAULT NULL,
  ncc_b_c text DEFAULT NULL,
  ncc_b_c_certificate text DEFAULT NULL,
  nss_day_camp text DEFAULT NULL,
  nss_day_camp_certificate text DEFAULT NULL,
  serving_retired_defense_employees_relatives text DEFAULT NULL,
  serving_retired_defense_employees_relatives_cert text DEFAULT NULL,
  has_migration_certificate text DEFAULT NULL,
  migration_certificate text DEFAULT NULL,
  has_transfer_certificate text DEFAULT NULL,
  transfer_certificate text DEFAULT NULL,
  photo text DEFAULT NULL,
  signature text DEFAULT NULL,
  category_certificate text DEFAULT NULL,
  pwd_certificate text DEFAULT NULL,
  id_proof_certificate text DEFAULT NULL,
  domicile_certificate text DEFAULT NULL,
  existing_uni_student_certificate text DEFAULT NULL,
  income_certificate text DEFAULT NULL,
  km_certificate text DEFAULT NULL,
  cw_certificate text DEFAULT NULL,
  pm_certificate text DEFAULT NULL,
  ex_serviceman_certificate text DEFAULT NULL,
  dependent_freedom_fighter text DEFAULT NULL,
  sgc_certificate text DEFAULT NULL,
  defence_personel_certificate text DEFAULT NULL,
  x_upload text DEFAULT NULL,
  xii_upload text DEFAULT NULL,
  pdf_application_form text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE students_details_master (
  master_id int(11) NOT NULL,
  student_reference_id varchar(255) DEFAULT NULL,
  institution_code varchar(50) NOT NULL,
  admission_no varchar(50) DEFAULT NULL,
  admission_date date DEFAULT NULL,
  admission_feepayment_time time DEFAULT NULL,
  class varchar(20) DEFAULT NULL,
  section varchar(10) DEFAULT NULL,
  stream varchar(50) DEFAULT NULL,
  batch_year varchar(20) DEFAULT NULL,
  admission_scheme varchar(50) DEFAULT 'NOT APPLICABLE',
  pr_no int(11) DEFAULT NULL,
  roll_number int(11) DEFAULT NULL,
  student_name varchar(100) DEFAULT NULL,
  gender varchar(50) DEFAULT NULL,
  student_category varchar(5) DEFAULT NULL,
  date_of_birth date DEFAULT NULL,
  religion varchar(50) DEFAULT NULL,
  blood_group varchar(10) DEFAULT NULL,
  email_address varchar(100) DEFAULT NULL,
  full_address text DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  pin_code int(11) DEFAULT NULL,
  mobile_number bigint(20) DEFAULT NULL,
  alt_mobile_number bigint(20) DEFAULT NULL,
  fathers_mobile_number bigint(20) DEFAULT NULL,
  mothers_mobile_number bigint(20) DEFAULT NULL,
  fathers_name varchar(100) DEFAULT NULL,
  fathers_occupation varchar(100) DEFAULT NULL,
  mothers_name varchar(100) DEFAULT NULL,
  mothers_occupation varchar(100) DEFAULT NULL,
  fathers_occupation_category varchar(50) DEFAULT NULL,
  mothers_occupation_category varchar(50) DEFAULT NULL,
  nationality varchar(50) DEFAULT NULL,
  mother_tongue varchar(50) DEFAULT NULL,
  name_of_the_institution_attended_earlier varchar(100) DEFAULT NULL,
  passsing_percentage decimal(5,2) DEFAULT NULL,
  board_name varchar(100) DEFAULT NULL,
  passing_year year(4) DEFAULT NULL,
  xii_stream varchar(50) DEFAULT NULL,
  xii_max_marks int(11) DEFAULT NULL,
  xii_marks_obtained int(11) DEFAULT NULL,
  xii_sub_combination varchar(100) DEFAULT NULL,
  xii_passing_class varchar(50) DEFAULT NULL,
  pwd_category_and_Percentage varchar(100) DEFAULT NULL,
  urban_rural_category varchar(50) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  is_active int(11) NOT NULL DEFAULT 1,
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  uploaded_file_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE student_fee_transactions (
  fees_trans_id int(11) NOT NULL,
  institution_code varchar(50) NOT NULL,
  uploaded_file_id int(11) NOT NULL,
  fees_table_ref_id varchar(255) DEFAULT NULL,
  institute_name varchar(255) DEFAULT NULL,
  branch_name varchar(255) NOT NULL,
  student_name varchar(255) DEFAULT NULL,
  email_address varchar(255) DEFAULT NULL,
  mobile_no varchar(255) DEFAULT NULL,
  course_name varchar(255) DEFAULT NULL,
  registration_code varchar(50) DEFAULT NULL,
  qfix_ref_no varchar(255) DEFAULT NULL,
  payment_status varchar(15) DEFAULT NULL,
  installment_no varchar(100) DEFAULT NULL,
  total_amt decimal(10,2) DEFAULT NULL,
  amount_paid decimal(10,2) DEFAULT NULL,
  remaining_amount decimal(12,2) NOT NULL,
  fees_paid_date date DEFAULT NULL,
  due_date date NOT NULL,
  fees_id bigint(20) DEFAULT NULL,
  transaction_id varchar(255) DEFAULT NULL,
  fees_category text DEFAULT NULL,
  payment_option varchar(100) DEFAULT NULL,
  payment_details varchar(30) DEFAULT NULL,
  cheque_dd_no varchar(255) DEFAULT NULL,
  payment_mode varchar(100) DEFAULT NULL,
  payment_reference_details varchar(50) NOT NULL,
  settlement_date date DEFAULT NULL,
  division_name varchar(100) DEFAULT NULL,
  bank_reference_no varchar(255) DEFAULT NULL,
  late_payment_charges decimal(10,2) DEFAULT NULL,
  refund_amount decimal(12,2) DEFAULT NULL,
  refund_date date DEFAULT NULL,
  refund_status varchar(50) DEFAULT NULL,
  vvm_online_offline_live_account decimal(12,2) DEFAULT NULL,
  vva_pre_primary_online_offline_live_account decimal(12,2) DEFAULT NULL,
  rms_secondary_school_76503022 decimal(12,2) DEFAULT NULL,
  sdcce_commerce_economics_76502948 decimal(12,2) DEFAULT NULL,
  sdcce_mcom_76502950 decimal(12,2) DEFAULT NULL,
  sdcce_bba_76502953 decimal(12,2) DEFAULT NULL,
  sdcce_bcom_nsa_76502893 decimal(12,2) DEFAULT NULL,
  sdcce_pgdft_76078365 decimal(12,2) DEFAULT NULL,
  sdcce_b_voc_76502967 decimal(12,2) DEFAULT NULL,
  tuition_fees decimal(12,2) DEFAULT NULL,
  term_fees decimal(12,2) DEFAULT NULL,
  pupils_fund decimal(12,2) DEFAULT NULL,
  activity_fees decimal(12,2) DEFAULT NULL,
  admission_fees decimal(12,2) DEFAULT NULL,
  registration_fees decimal(12,2) DEFAULT NULL,
  development_fund decimal(12,2) DEFAULT NULL,
  refundable_deposit decimal(12,2) DEFAULT NULL,
  general_deposit decimal(12,2) DEFAULT NULL,
  enrolment_fee decimal(12,2) DEFAULT NULL,
  laboratory_deposit decimal(12,2) DEFAULT NULL,
  laboratory_fee decimal(12,2) DEFAULT NULL,
  uni_registration_fees decimal(12,2) DEFAULT NULL,
  library_fees decimal(12,2) DEFAULT NULL,
  gymkhana_fees decimal(12,2) DEFAULT NULL,
  other_fees decimal(12,2) DEFAULT NULL,
  student_aid_fees decimal(12,2) DEFAULT NULL,
  library_deposit decimal(12,2) DEFAULT NULL,
  caution_money_deposit decimal(12,2) DEFAULT NULL,
  lab_fees decimal(12,2) DEFAULT NULL,
  uni_administration_fees decimal(12,2) DEFAULT NULL,
  development_fees decimal(12,2) DEFAULT NULL,
  it_fees decimal(12,2) DEFAULT NULL,
  examination_fees decimal(12,2) DEFAULT NULL,
  pta_fees decimal(12,2) DEFAULT NULL,
  university_registration_fees decimal(12,2) DEFAULT NULL,
  laboratory_fees decimal(12,2) DEFAULT NULL,
  university_administration_fees decimal(12,2) DEFAULT NULL,
  library_id_card_etc decimal(12,2) DEFAULT NULL,
  computer_lab_fees decimal(12,2) DEFAULT NULL,
  information_technology_fees decimal(12,2) DEFAULT NULL,
  iaims_fees_dhe decimal(12,2) DEFAULT NULL,
  iams_fees decimal(12,2) DEFAULT NULL,
  alumni_registration_fees decimal(12,2) DEFAULT NULL,
  academic_restructuring_and_development_fees decimal(12,2) DEFAULT NULL,
  magazine_academic_diary_placement_brochure decimal(12,2) DEFAULT NULL,
  id_card_fees decimal(12,2) DEFAULT NULL,
  iaims_fees decimal(12,2) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE users (
  id int(11) NOT NULL,
  full_name varchar(255) NOT NULL,
  username varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  role varchar(50) NOT NULL,
  password_hash varchar(255) NOT NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  institution_code varchar(255) DEFAULT NULL,
  last_login timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE user_upload_details (
  upload_id int(11) NOT NULL,
  institution_code varchar(50) NOT NULL,
  file_name varchar(255) NOT NULL,
  table_type varchar(100) NOT NULL,
  uploaded_on datetime DEFAULT current_timestamp(),
  academic_year varchar(10) DEFAULT NULL,
  academic_quarter varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE institutions
  ADD PRIMARY KEY (institute_id),
  ADD UNIQUE KEY institute_code (institution_code);

ALTER TABLE stg_fees_details
  ADD PRIMARY KEY (stg_id),
  ADD KEY uploaded_file_id (uploaded_file_id);

ALTER TABLE stg_rms_vva_student_details
  ADD PRIMARY KEY (stg_id),
  ADD KEY uploaded_file_id (uploaded_file_id);

ALTER TABLE stg_sdcce_grkcl_student_details
  ADD PRIMARY KEY (stg_id),
  ADD KEY uploaded_file_id (uploaded_file_id);

ALTER TABLE students_details_master
  ADD PRIMARY KEY (master_id),
  ADD UNIQUE KEY student_reference_id (student_reference_id);

ALTER TABLE student_fee_transactions
  ADD PRIMARY KEY (fees_trans_id);

ALTER TABLE users
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY username (username),
  ADD UNIQUE KEY email (email),
  ADD KEY fk_institution (institution_code);

ALTER TABLE user_upload_details
  ADD PRIMARY KEY (upload_id);


ALTER TABLE institutions
  MODIFY institute_id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

ALTER TABLE stg_fees_details
  MODIFY stg_id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE stg_rms_vva_student_details
  MODIFY stg_id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE stg_sdcce_grkcl_student_details
  MODIFY stg_id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE students_details_master
  MODIFY master_id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE student_fee_transactions
  MODIFY fees_trans_id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE users
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE user_upload_details
  MODIFY upload_id int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE stg_fees_details
  ADD CONSTRAINT stg_fees_details_ibfk_1 FOREIGN KEY (uploaded_file_id) REFERENCES user_upload_details (upload_id);

ALTER TABLE stg_rms_vva_student_details
  ADD CONSTRAINT stg_rms_vva_student_details_ibfk_1 FOREIGN KEY (uploaded_file_id) REFERENCES user_upload_details (upload_id);

ALTER TABLE stg_sdcce_grkcl_student_details
  ADD CONSTRAINT stg_sdcce_grkcl_student_details_ibfk_1 FOREIGN KEY (uploaded_file_id) REFERENCES user_upload_details (upload_id);

ALTER TABLE users
  ADD CONSTRAINT fk_institution FOREIGN KEY (institution_code) REFERENCES institutions (institution_code);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
